- name: "Join a Swarm"
  docker_swarm:
    state: join
    remote_addrs: [ "{{ hostvars['man1']['ansible_default_ipv4']['address'] }}:2377" ]
    advertise_addr: swarm-worker
    join_token: "{{ hostvars['manager']['swarm_info']['swarm_facts']['JoinTokens']['Woker'] }}"
