- name: "Join a Swarm"
  docker_swarm:
    state: join
    remote_addrs: ['manager:2377']
    advertise_addr: swarm-worker
    join_token: "{{ hostvars['manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
